controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_task_index:
    path: /task
    controller: App\Controller\TaskController::index

app_home:
    path: /
    controller: App\Controller\HomeController::index